### ISSUE TITLE
 IndexError: list index out of range

### ISSUE THREAD

**Issue by iramishtiaq** [Franck-Dernoncourt/NeuroNER#2]
i am getting these warning while running neuroner

`epoch_elapsed_training_time:` 331.644915 seconds assess_model on dataset_type: train C:\Users\erame\AppData\Local\Programs\Python\Python35\lib\site-packages\matplotlib\artist.py:233: MatplotlibDeprecationWarning: get_axes has been deprecated in mpl 1.5, please use the axes property. A removal date has not been set. stacklevel=1) C:\Users\erame\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples. 'precision', 'predicted', average, warn_for) C:\Users\erame\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples. 'recall', 'true', average, warn_for) assess_model on dataset_type: valid assess_model on dataset_type: test shell_command: perl .\conlleval < ..\output\en_2017-04-21_07-36-25-322798\000_014986_train.txt > ..\output\en_2017-04-21_07-36-25-322798\000_014986_train.txt_conll_evaluation.txt 'perl' is not recognized as an internal or external command, operable program or batch file. Traceback (most recent call last): File "main.py", line 442, in <module> main() File "main.py", line 383, in main conll_parsed_output = utils_nlp.get_parsed_conll_output(conll_output_filepath) File "C:\Users\erame\AppData\Local\Programs\Python\Python35\NeuroNER-master\src\utils_nlp.py", line 42, in get_parsed_conll_output line = conll_output[1].split() IndexError: list index out of range`

**Comment by Franck-Dernoncourt** [comment]
The key is `'perl' is not recognized as an internal or external`.

You need to install Perl (because the official CoNLL-2003 evaluation script is written in Perl). You can download Perl from http://strawberryperl.com

Make sure the `perl.exe` binary is in your `Path` system environment variable, which you can check as follows:

![](http://neuroner.com/perl2.png "")

To add perl in your `Path` system environment variable:

![image](https://cloud.githubusercontent.com/assets/15331/25314502/342002da-2813-11e7-8c0b-5d91a686ccfb.png)

**Comment by iramishtiaq** [comment]
thankyou :) it's working!
